export * as schema from "./schema.js";
export {
  getDb,
  getMaintenanceDb,
  closeDb,
  pingDb,
  checkAppRoleRls,
  checkMaintenanceRoleRls,
  checkMaintenanceConnection,
  assertMaintenanceRoleBypassesRls,
  type Db,
  type RoleRlsStatus,
  type MaintenanceConnectionStatus,
} from "./client.js";
export {
  appendAudit,
  verifyAuditChain,
  verifyChainRows,
  computeAuditHash,
  GENESIS_HASH,
  type AuditEntry,
  type AuditScheme,
  type VerifiableRow,
  type ChainVerification,
} from "./audit.js";
export {
  anchorAuditChain,
  listAnchors,
  verifyAnchors,
  readAnchorFile,
  buildTimestampRequest,
  type AnchorVerification,
} from "./anchors.js";
export {
  upsertCaseForRecord,
  getCaseByKey,
  getCasesByKeys,
  getCaseByWorkflowId,
  updateCaseStatus,
  listCases,
  listOpenMonitoringCases,
  listCasesAwaitingHuman,
  AWAITING_HUMAN_STATUSES,
  bumpFeedMiss,
  resetFeedMiss,
  workflowIdForKey,
  MONITORING_STATUSES,
  type OpenMonitoringCase,
} from "./cases.js";
export {
  approveProtocolVersion,
  draftProtocolVersion,
  getApprovedProtocol,
  listProtocols,
  listProtocolVersions,
  type DraftProtocolInput,
  type ProtocolSummary,
} from "./protocols.js";
export {
  upsertUserByOidc,
  getUserByOidc,
  getUserRoles,
  getRolesForUsers,
  isUserInOrg,
  getSyntheticUser,
  syntheticUserIdForLabel,
  assignRole,
  revokeRole,
  listUsers,
  setUserDisabled,
  SYNTHETIC_USER_IDS,
  type SyntheticUser,
  type UpsertUserInput,
} from "./users.js";
export {
  SEED_ORG_ID,
  SEED_ORG_SLUG,
  SECOND_ORG_ID,
  SECOND_ORG_SLUG,
  SECOND_ORG_NAME,
  createOrganization,
  getOrganization,
  listOrganizations,
} from "./orgs.js";
export { withOrgDb, withBypassDb } from "./org-context.js";
export { getKpis, type Kpis } from "./metrics.js";
export { getOpsMetrics, type OpsMetrics } from "./ops-metrics.js";
export {
  getEscalationPolicy,
  listEscalationPolicies,
  upsertEscalationPolicy,
  listRoleRecipients,
  recordAcknowledgment,
  listAcknowledgments,
} from "./escalation.js";
export {
  listShadowRuns,
  listShadowRunsForClass,
  recordShadowRun,
  shadowStatsByClass,
  type ShadowClassStats,
} from "./shadow.js";
export { getLlmSpend, recordLlmSpend, utcDay, type DailySpend } from "./spend.js";
export { countDemoRunsSince, reserveDemoRun } from "./demo-runs.js";
export {
  API_SCOPES,
  findActiveApiKeyByPlaintext,
  generateApiKey,
  hashApiKey,
  isApiScope,
  issueApiKey,
  listApiKeys,
  reserveApiKeyRequest,
  revokeApiKey,
  touchApiKeyUsed,
  type ApiScope,
  type IssueApiKeyInput,
} from "./api-keys.js";
export { feedFreshness, recordFeedRecords, type FeedFreshness } from "./feeds.js";
export {
  listAlertRules,
  createAlertRule,
  updateAlertRule,
  deleteAlertRule,
  lastFiredByRule,
  recordAlertEvents,
  recordAlertDeliveries,
  listAlertEvents,
  type AlertRuleInput,
  type AlertEventInput,
} from "./alerts.js";
export {
  recordDailyBrief,
  previousDailyBrief,
  listDailyBriefs,
  DEGRADED_REASONS,
  type DegradedReason,
  type DailyBriefInput,
} from "./briefs.js";
export {
  dedupeByKey,
  upsertSignals,
  bumpSignalFeedMiss,
  listSignals,
  getSignalByKey,
  recordScoreSnapshots,
  recordEvidence,
  listEvidenceForSignal,
  latestScoresForSignals,
  FEED_ABSENT_THRESHOLD,
  type ListSignalsOptions,
  type ScoreSnapshotInput,
  type EvidenceInput,
} from "./signals.js";
export { importCatalog, RefusedImportError, type ImportResult } from "./catalog.js";
export {
  listSignalsPage,
  getSignalForApi,
  listScoresPage,
  listCatalogItemsPage,
  type Page,
  type PagedListOptions,
  type SignalListRow,
  type ScoreListRow,
  type CatalogItemListRow,
} from "./public-lists.js";
  retentionPlan,
  sweepOrgRetention,
  totalRemoved,
  RETENTION_KINDS,
  RETENTION_BATCH_SIZE,
  RETAINED_FOREVER,
  type RetentionKind,
  type RetentionWindows,
  type RetentionCounts,
  type RetentionSweepResult,
} from "./retention.js";
export type {
  OrganizationRow,
  NewOrganizationRow,
  ApiKeyRow,
  NewApiKeyRow,
  ApiKeyRequestRow,
  DemoRunRow,
  LlmSpendRow,
  EscalationPolicyRow,
  EscalationStep,
  AcknowledgmentRow,
  UserRow,
  NewUserRow,
  UserRoleRow,
  CaseRow,
  NewCaseRow,
  AuditRow,
  AuditAnchorRow,
  FeedRecordRow,
  ProtocolRow,
  ProtocolVersionRow,
  NewProtocolVersionRow,
  ShadowRunRow,
  NewShadowRunRow,
  DailyBriefRow,
} from "./schema.js";
export {
  BURN_WINDOW_DAYS,
  catalogExposure,
  exposureFacts,
  matchSignalToCatalog,
  matchSignalsToCatalog,
  summarizeExposure,
  type CatalogExposureReading,
  type ExposureFacts,
} from "./matching.js";
